mpe.nlp.engine=duui
mpe.duui.endpoint=http://spacy.service.component.duui.texttechnologylab.org
mpe.duui.token=
mpe.duui.timeoutSeconds=30
duui.mode=remote
duui.workers=1
duui.spacy.target=http://spacy.service.component.duui.texttechnologylab.org
duui.gervader.target=http://gervader.service.component.duui.texttechnologylab.org
duui.parlbert_topic.target=http://parlbert.service.component.duui.texttechnologylab.org
duui.spacy.param.language=de
duui.param.selection=sentences
duui.param.view=speech
